""" 
Module: settings
"""

import os

SNAPSHOT_REGISTRY_REGISTRY=os.environ.get('SNAPSHOT_REGISTRY_REGISTRY')
SNAPSHOT_REGISTRY_PASSWORD=os.environ.get('SNAPSHOT_REGISTRY_PASSWORD')
SNAPSHOT_REGISTRY_USERNAME=os.environ.get('SNAPSHOT_REGISTRY_USERNAME')
SNAPSHOT_CONTAINER_TARGET_IMAGE = os.environ.get('SNAPSHOT_CONTAINER_TARGET_IMAGE')
SNAPSHOT_CONTAINER_NAME=os.environ.get('SNAPSHOT_CONTAINER_NAME')
ABCDESKTOP_USERNAME=os.environ.get('ABCDESKTOP_USERNAME')
ABCDESKTOP_USERID= os.environ.get('ABCDESKTOP_USERID')

# DEUB | INFO | ERROR
DEBUG_LEVEL="DEBUG"
